name: 编译 LEDE
#on:
#  repository_dispatch:
on:
  push

env:
  LEDE_REPO_URL: https://github.com/coolsnowwolf/lede.git
  TZ: Asia/Shanghai
  IP: 192.168.1.88



jobs:
  build-openwrt:
    runs-on: ubuntu-latest
#    name: Build ${{ matrix.target }}
#    strategy:
#      fail-fast: false
#      matrix:
#        target: [ ${ { github.event.client_payload.target } } ]

    steps:
      - name: 检出当前工程
        uses: actions/checkout@main

      - name: 检查工作环境
        run: |
          echo "LEDE 源码地址: $LEDE_REPO_URL"
          echo "系统: ${{ runner.os }}"
          echo "工作空间: ${{ github.workspace }}"
          echo "查看系统发行版:"
          cat /etc/lsb-release
          echo "core $(($(nproc)+1))"

      - name: 初始化执行环境
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install build-essential clang flex g++ gawk gcc-multilib gettext \
          git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev swig libpython3-dev aria2 jq subversion qemu-utils ccache rename libelf-dev device-tree-compiler
          sudo -E apt-get -qq purge azure-cli ghc* zulu* hhvm llvm* firefox powershell openjdk* dotnet* google* mysql* php* android*
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo timedatectl set-timezone "$TZ"

      - name: 下载lede源码
        run: |
          git clone $LEDE_REPO_URL
          ls

      - name: 初始化配置
        run: |
          cp lede-config/x86_config lede/.config
          cd lede
          echo "修改IP地址为: $IP"
          sed -i 's/192\.168\.1\.1/$IP/g' ./package/base-files/files/bin/config_generate
          cat ./package/base-files/files/bin/config_generate
          cat .config

      - name: 更新feeds
        run: |
          cd lede
          echo "src-git sirpdboy https://github.com/sirpdboy/sirpdboy-package" >> ./feeds.conf.default
          echo "src-git kiddin9 https://github.com/kiddin9/openwrt-packages.git" >> ./feeds.conf.default
          cat ./feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: make download
        run: |
          cd lede
          make download -j$(($(nproc)+1))
#
#      - name: 开始编译
#        run: |
#          cd lede
#          make V=s -j$(($(nproc)+1))
      - name: 增加缓存
        id: cache
        uses: actions/cache@main
        with:
          path: ${{ github.workspace }}/lede
          key: cache-key-lede-${{ matrix.target }}
      #          restore-keys: |
      #            cache-key-lede-${{ matrix.target }}

#      - name: 开始打包
#        run: |
#          cd lede
#          tar -czvf /tmp/openwrt.tar.gz bin/targets
#
#      - name: 上传文件
#        uses: actions/upload-artifact@main
#        with:
#          name: openwrt.tar.gz
#          path: /tmp/openwrt.tar.gz
#          if-no-files-found: error
