name: 矩阵测试
on: 
  repository_dispatch:
    types:
      - test
jobs:
  example_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       version: ${{ github.event.client_payload.versions }}
    steps:
      - name: check node version1
        run: |
          node -v
          npm -v
      - name: 设置node版本
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.version }}
      - name: check node version2
        run: |
          node -v
          npm -v