# 工作流程名字
name: 项目构建
# 触发工作流程事件
#on: [push]
on:
  push:
    branches:
      - master
env: 
  PROJECT_NAME: learn-test
# 流程子作业
jobs:
  java-build:
    runs-on: ubuntu-latest
    name: 编译一个java项目
    steps:
      - name: 检出项目
        uses: actions/checkout@v3.2.0

      - name: 配置-缓存加速
        uses: actions/cache@v3.2.1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: 查看workspace
        run: ls ${{github.workspace}}

      - name: 配置-新java环境
        uses: actions/setup-java@v3.9.0
        with:
          distribution: zulu
          java-version: 8

      - name: 检查-java环境
        run: java -version

      - name: 检查-maven环境
        run: mvn -v

      - name: 执行-maven打包
        run: mvn clean package -Dmaven.test.skip=true

      - name: 执行-发布包
        uses: actions/upload-artifact@v3.1.1
        with: 
          name: ${{ env.PROJECT_NAME }}.jar
          path: ${{ github.workspace }}/target/${{ env.PROJECT_NAME }}.jar
          if-no-files-found: error
          # 文件保留天数
          retention-days: 1